# Generated by Django 5.2.5 on 2025-09-02 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('division1', models.IntegerField(default=0)),
                ('division2', models.IntegerField(default=0)),
                ('division3', models.IntegerField(default=0)),
                ('division4', models.IntegerField(default=0)),
                ('division0', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0.0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.school')),
            ],
            options={
                'ordering': ['gpa', '-total'],
                'unique_together': {('school', 'exam', 'year')},
            },
        ),
    ]
